{
  "sites": [
    {
      "id": "<TBD>",
      "display_name": "<TBD>",
      "purpose": "<TBD>"
    },
    {
      "id": "<TBD>",
      "display_name": "<TBD>",
      "purpose": "<TBD>"
    }
  ]
}
